/**
 * AUTO-GENERATED by `npm run supabase:types`.
 * Source: local migration workspace
 * Do not edit by hand.
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      api_integrations: {
        Row: {
          api_key_hash: string | null
          key_prefix: string | null
          outlet_id: string
          updated_at: string | null
          webhook_url: string | null
        }
        Insert: {
          api_key_hash?: string | null
          key_prefix?: string | null
          outlet_id: string
          updated_at?: string | null
          webhook_url?: string | null
        }
        Update: {
          api_key_hash?: string | null
          key_prefix?: string | null
          outlet_id?: string
          updated_at?: string | null
          webhook_url?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "api_integrations_outlet_id_fkey"
            columns: ["outlet_id"]
            isOneToOne: true
            referencedRelation: "outlets"
            referencedColumns: ["outlet_id"]
          },
        ]
      }
      appointments: {
        Row: {
          client_id: string | null
          created_at: string | null
          customer_id: string | null
          date: string
          end_time: string | null
          id: string
          is_on_duty: boolean | null
          outlet_id: string
          reminder_sent: boolean | null
          sale_id: string | null
          service_id: string | null
          source: string | null
          source_sale_id: string | null
          staff_id: string | null
          status: string | null
          time: string
        }
        Insert: {
          client_id?: string | null
          created_at?: string | null
          customer_id?: string | null
          date: string
          end_time?: string | null
          id: string
          is_on_duty?: boolean | null
          outlet_id: string
          reminder_sent?: boolean | null
          sale_id?: string | null
          service_id?: string | null
          source?: string | null
          source_sale_id?: string | null
          staff_id?: string | null
          status?: string | null
          time: string
        }
        Update: {
          client_id?: string | null
          created_at?: string | null
          customer_id?: string | null
          date?: string
          end_time?: string | null
          id?: string
          is_on_duty?: boolean | null
          outlet_id?: string
          reminder_sent?: boolean | null
          sale_id?: string | null
          service_id?: string | null
          source?: string | null
          source_sale_id?: string | null
          staff_id?: string | null
          status?: string | null
          time?: string
        }
        Relationships: [
          {
            foreignKeyName: "appointments_outlet_id_fkey"
            columns: ["outlet_id"]
            isOneToOne: false
            referencedRelation: "outlets"
            referencedColumns: ["outlet_id"]
          },
        ]
      }
      audit_logs: {
        Row: {
          action: string
          actor_user_id: string | null
          created_at: string
          id: string
          metadata: Json
          outlet_id: string | null
          reason: string | null
          target_id: string | null
          target_type: string
        }
        Insert: {
          action: string
          actor_user_id?: string | null
          created_at?: string
          id?: string
          metadata?: Json
          outlet_id?: string | null
          reason?: string | null
          target_id?: string | null
          target_type: string
        }
        Update: {
          action?: string
          actor_user_id?: string | null
          created_at?: string
          id?: string
          metadata?: Json
          outlet_id?: string | null
          reason?: string | null
          target_id?: string | null
          target_type?: string
        }
        Relationships: [
          {
            foreignKeyName: "audit_logs_outlet_id_fkey"
            columns: ["outlet_id"]
            isOneToOne: false
            referencedRelation: "outlets"
            referencedColumns: ["outlet_id"]
          },
        ]
      }
      billing_customers: {
        Row: {
          created_at: string
          email: string | null
          outlet_id: string
          stripe_customer_id: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          email?: string | null
          outlet_id: string
          stripe_customer_id: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          email?: string | null
          outlet_id?: string
          stripe_customer_id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "billing_customers_outlet_id_fkey"
            columns: ["outlet_id"]
            isOneToOne: true
            referencedRelation: "outlets"
            referencedColumns: ["outlet_id"]
          },
        ]
      }
      billing_events: {
        Row: {
          event_type: string
          id: string
          livemode: boolean
          outlet_id: string | null
          payload: Json
          received_at: string
          stripe_created_at: string | null
        }
        Insert: {
          event_type: string
          id: string
          livemode?: boolean
          outlet_id?: string | null
          payload: Json
          received_at?: string
          stripe_created_at?: string | null
        }
        Update: {
          event_type?: string
          id?: string
          livemode?: boolean
          outlet_id?: string | null
          payload?: Json
          received_at?: string
          stripe_created_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "billing_events_outlet_id_fkey"
            columns: ["outlet_id"]
            isOneToOne: false
            referencedRelation: "outlets"
            referencedColumns: ["outlet_id"]
          },
        ]
      }
      clients: {
        Row: {
          birthday: string | null
          created_at: string | null
          credit: number | null
          email: string | null
          ethnic: string | null
          gender: string | null
          ic: string | null
          id: string
          last_import_id: string | null
          marital: string | null
          marketing_email_consent: boolean
          marketing_sms_consent: boolean
          marketing_unsubscribed_at: string | null
          marketing_whatsapp_consent: boolean
          member_tier: string | null
          name: string
          notes: string | null
          outlet_id: string
          outstanding: number | null
          phone: string | null
          points: number | null
          source: string | null
          tag: string | null
          voucher_count: number | null
        }
        Insert: {
          birthday?: string | null
          created_at?: string | null
          credit?: number | null
          email?: string | null
          ethnic?: string | null
          gender?: string | null
          ic?: string | null
          id: string
          last_import_id?: string | null
          marital?: string | null
          marketing_email_consent?: boolean
          marketing_sms_consent?: boolean
          marketing_unsubscribed_at?: string | null
          marketing_whatsapp_consent?: boolean
          member_tier?: string | null
          name?: string
          notes?: string | null
          outlet_id: string
          outstanding?: number | null
          phone?: string | null
          points?: number | null
          source?: string | null
          tag?: string | null
          voucher_count?: number | null
        }
        Update: {
          birthday?: string | null
          created_at?: string | null
          credit?: number | null
          email?: string | null
          ethnic?: string | null
          gender?: string | null
          ic?: string | null
          id?: string
          last_import_id?: string | null
          marital?: string | null
          marketing_email_consent?: boolean
          marketing_sms_consent?: boolean
          marketing_unsubscribed_at?: string | null
          marketing_whatsapp_consent?: boolean
          member_tier?: string | null
          name?: string
          notes?: string | null
          outlet_id?: string
          outstanding?: number | null
          phone?: string | null
          points?: number | null
          source?: string | null
          tag?: string | null
          voucher_count?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "clients_outlet_id_fkey"
            columns: ["outlet_id"]
            isOneToOne: false
            referencedRelation: "outlets"
            referencedColumns: ["outlet_id"]
          },
        ]
      }
      credit_history: {
        Row: {
          amount: number | null
          client_id: string
          id: string
          new_balance: number | null
          outlet_id: string | null
          staff_name: string | null
          staff_remark: string | null
          timestamp: string | null
          transaction_id: string | null
          type: string
        }
        Insert: {
          amount?: number | null
          client_id: string
          id?: string
          new_balance?: number | null
          outlet_id?: string | null
          staff_name?: string | null
          staff_remark?: string | null
          timestamp?: string | null
          transaction_id?: string | null
          type: string
        }
        Update: {
          amount?: number | null
          client_id?: string
          id?: string
          new_balance?: number | null
          outlet_id?: string | null
          staff_name?: string | null
          staff_remark?: string | null
          timestamp?: string | null
          transaction_id?: string | null
          type?: string
        }
        Relationships: [
          {
            foreignKeyName: "credit_history_client_id_fkey"
            columns: ["client_id"]
            isOneToOne: false
            referencedRelation: "clients"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "credit_history_outlet_id_fkey"
            columns: ["outlet_id"]
            isOneToOne: false
            referencedRelation: "outlets"
            referencedColumns: ["outlet_id"]
          },
        ]
      }
      customer_profiles: {
        Row: {
          created_at: string
          preferences: Json
          updated_at: string
          user_id: string
        }
        Insert: {
          created_at?: string
          preferences?: Json
          updated_at?: string
          user_id: string
        }
        Update: {
          created_at?: string
          preferences?: Json
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "customer_profiles_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: true
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      frontend_customers: {
        Row: {
          booking_history_refs: Json | null
          client_id: string | null
          created_at: string | null
          email: string | null
          id: string
          last_appointment_id: string | null
          last_booked_at: string | null
          name: string | null
          outlet_id: string | null
          phone: string | null
          source: string | null
          updated_at: string | null
        }
        Insert: {
          booking_history_refs?: Json | null
          client_id?: string | null
          created_at?: string | null
          email?: string | null
          id: string
          last_appointment_id?: string | null
          last_booked_at?: string | null
          name?: string | null
          outlet_id?: string | null
          phone?: string | null
          source?: string | null
          updated_at?: string | null
        }
        Update: {
          booking_history_refs?: Json | null
          client_id?: string | null
          created_at?: string | null
          email?: string | null
          id?: string
          last_appointment_id?: string | null
          last_booked_at?: string | null
          name?: string | null
          outlet_id?: string | null
          phone?: string | null
          source?: string | null
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "frontend_customers_outlet_id_fkey"
            columns: ["outlet_id"]
            isOneToOne: false
            referencedRelation: "outlets"
            referencedColumns: ["outlet_id"]
          },
        ]
      }
      marketing_audiences: {
        Row: {
          created_at: string
          created_by: string | null
          criteria: Json
          description: string | null
          id: string
          name: string
          outlet_id: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          created_by?: string | null
          criteria?: Json
          description?: string | null
          id?: string
          name: string
          outlet_id: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          created_by?: string | null
          criteria?: Json
          description?: string | null
          id?: string
          name?: string
          outlet_id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "marketing_audiences_outlet_id_fkey"
            columns: ["outlet_id"]
            isOneToOne: false
            referencedRelation: "outlets"
            referencedColumns: ["outlet_id"]
          },
        ]
      }
      marketing_campaign_deliveries: {
        Row: {
          attempt_count: number
          campaign_id: string
          channel: string
          client_id: string
          id: string
          last_error: string | null
          outlet_id: string
          processed_at: string | null
          provider: string | null
          provider_message_id: string | null
          queued_at: string
          recipient_masked: string | null
          sent_at: string | null
          status: string
          updated_at: string
        }
        Insert: {
          attempt_count?: number
          campaign_id: string
          channel: string
          client_id: string
          id?: string
          last_error?: string | null
          outlet_id: string
          processed_at?: string | null
          provider?: string | null
          provider_message_id?: string | null
          queued_at?: string
          recipient_masked?: string | null
          sent_at?: string | null
          status?: string
          updated_at?: string
        }
        Update: {
          attempt_count?: number
          campaign_id?: string
          channel?: string
          client_id?: string
          id?: string
          last_error?: string | null
          outlet_id?: string
          processed_at?: string | null
          provider?: string | null
          provider_message_id?: string | null
          queued_at?: string
          recipient_masked?: string | null
          sent_at?: string | null
          status?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "marketing_campaign_deliveries_campaign_id_fkey"
            columns: ["campaign_id"]
            isOneToOne: false
            referencedRelation: "marketing_campaigns"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "marketing_campaign_deliveries_client_id_fkey"
            columns: ["client_id"]
            isOneToOne: false
            referencedRelation: "clients"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "marketing_campaign_deliveries_outlet_id_fkey"
            columns: ["outlet_id"]
            isOneToOne: false
            referencedRelation: "outlets"
            referencedColumns: ["outlet_id"]
          },
        ]
      }
      marketing_campaigns: {
        Row: {
          audience_id: string | null
          channel: string
          created_at: string
          created_by: string | null
          id: string
          message: string
          name: string
          objective: string
          offer: Json
          outlet_id: string
          scheduled_at: string | null
          status: string
          subject: string | null
          updated_at: string
        }
        Insert: {
          audience_id?: string | null
          channel: string
          created_at?: string
          created_by?: string | null
          id?: string
          message: string
          name: string
          objective?: string
          offer?: Json
          outlet_id: string
          scheduled_at?: string | null
          status?: string
          subject?: string | null
          updated_at?: string
        }
        Update: {
          audience_id?: string | null
          channel?: string
          created_at?: string
          created_by?: string | null
          id?: string
          message?: string
          name?: string
          objective?: string
          offer?: Json
          outlet_id?: string
          scheduled_at?: string | null
          status?: string
          subject?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "marketing_campaigns_audience_id_fkey"
            columns: ["audience_id"]
            isOneToOne: false
            referencedRelation: "marketing_audiences"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "marketing_campaigns_outlet_id_fkey"
            columns: ["outlet_id"]
            isOneToOne: false
            referencedRelation: "outlets"
            referencedColumns: ["outlet_id"]
          },
        ]
      }
      merchant_onboarding_drafts: {
        Row: {
          account_type: string | null
          auth_user_id: string
          completed_at: string | null
          created_at: string
          current_step: string
          payload: Json
          updated_at: string
        }
        Insert: {
          account_type?: string | null
          auth_user_id: string
          completed_at?: string | null
          created_at?: string
          current_step?: string
          payload?: Json
          updated_at?: string
        }
        Update: {
          account_type?: string | null
          auth_user_id?: string
          completed_at?: string | null
          created_at?: string
          current_step?: string
          payload?: Json
          updated_at?: string
        }
        Relationships: []
      }
      merchant_provision_requests: {
        Row: {
          created_at: string
          error_code: string | null
          outlet_id: string | null
          request_id: string
          status: string
          updated_at: string
          user_id: string
        }
        Insert: {
          created_at?: string
          error_code?: string | null
          outlet_id?: string | null
          request_id: string
          status?: string
          updated_at?: string
          user_id: string
        }
        Update: {
          created_at?: string
          error_code?: string | null
          outlet_id?: string | null
          request_id?: string
          status?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "merchant_provision_requests_outlet_id_fkey"
            columns: ["outlet_id"]
            isOneToOne: false
            referencedRelation: "outlets"
            referencedColumns: ["outlet_id"]
          },
        ]
      }
      onboarding_states: {
        Row: {
          booking_published: boolean
          completed_steps: Json
          created_at: string
          current_step: string
          first_service_created: boolean
          operations_configured: boolean
          outlet_id: string
          team_configured: boolean
          updated_at: string
        }
        Insert: {
          booking_published?: boolean
          completed_steps?: Json
          created_at?: string
          current_step?: string
          first_service_created?: boolean
          operations_configured?: boolean
          outlet_id: string
          team_configured?: boolean
          updated_at?: string
        }
        Update: {
          booking_published?: boolean
          completed_steps?: Json
          created_at?: string
          current_step?: string
          first_service_created?: boolean
          operations_configured?: boolean
          outlet_id?: string
          team_configured?: boolean
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "onboarding_states_outlet_id_fkey"
            columns: ["outlet_id"]
            isOneToOne: true
            referencedRelation: "outlets"
            referencedColumns: ["outlet_id"]
          },
        ]
      }
      outlet_invitations: {
        Row: {
          accepted_at: string | null
          accepted_by: string | null
          created_at: string
          created_by: string | null
          email: string
          expires_at: string
          id: string
          invited_by: string | null
          outlet_id: string
          role: string
          status: string
          token_hash: string
          updated_at: string
        }
        Insert: {
          accepted_at?: string | null
          accepted_by?: string | null
          created_at?: string
          created_by?: string | null
          email: string
          expires_at: string
          id?: string
          invited_by?: string | null
          outlet_id: string
          role: string
          status?: string
          token_hash: string
          updated_at?: string
        }
        Update: {
          accepted_at?: string | null
          accepted_by?: string | null
          created_at?: string
          created_by?: string | null
          email?: string
          expires_at?: string
          id?: string
          invited_by?: string | null
          outlet_id?: string
          role?: string
          status?: string
          token_hash?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "outlet_invitations_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["uid"]
          },
          {
            foreignKeyName: "outlet_invitations_outlet_id_fkey"
            columns: ["outlet_id"]
            isOneToOne: false
            referencedRelation: "outlets"
            referencedColumns: ["outlet_id"]
          },
        ]
      }
      outlet_members: {
        Row: {
          created_at: string
          id: string
          invited_by: string | null
          joined_at: string | null
          outlet_id: string
          role: string
          status: string
          updated_at: string
          user_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          invited_by?: string | null
          joined_at?: string | null
          outlet_id: string
          role: string
          status?: string
          updated_at?: string
          user_id: string
        }
        Update: {
          created_at?: string
          id?: string
          invited_by?: string | null
          joined_at?: string | null
          outlet_id?: string
          role?: string
          status?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "outlet_members_outlet_id_fkey"
            columns: ["outlet_id"]
            isOneToOne: false
            referencedRelation: "outlets"
            referencedColumns: ["outlet_id"]
          },
        ]
      }
      outlet_subscriptions: {
        Row: {
          cancel_at_period_end: boolean
          created_at: string
          current_period_end: string | null
          current_period_start: string | null
          id: string
          outlet_id: string
          status: string
          stripe_customer_id: string
          stripe_price_id: string | null
          trial_end: string | null
          updated_at: string
        }
        Insert: {
          cancel_at_period_end?: boolean
          created_at?: string
          current_period_end?: string | null
          current_period_start?: string | null
          id: string
          outlet_id: string
          status: string
          stripe_customer_id: string
          stripe_price_id?: string | null
          trial_end?: string | null
          updated_at?: string
        }
        Update: {
          cancel_at_period_end?: boolean
          created_at?: string
          current_period_end?: string | null
          current_period_start?: string | null
          id?: string
          outlet_id?: string
          status?: string
          stripe_customer_id?: string
          stripe_price_id?: string | null
          trial_end?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "outlet_subscriptions_outlet_id_fkey"
            columns: ["outlet_id"]
            isOneToOne: false
            referencedRelation: "outlets"
            referencedColumns: ["outlet_id"]
          },
        ]
      }
      outlets: {
        Row: {
          access_status: string
          account_limit: number
          address: Json | null
          address_display: string | null
          booking_slug: string | null
          business_hours: Json | null
          business_type: string | null
          created_at: string | null
          email: string | null
          is_active: boolean | null
          name: string
          onboarding_status: string
          outlet_id: string
          owner_user_id: string | null
          phone: string | null
          phone_number: string | null
          reviews: Json | null
          service_categories: Json | null
          settings: Json | null
          status: string
          timezone: string | null
          updated_at: string | null
          website: string | null
        }
        Insert: {
          access_status?: string
          account_limit?: number
          address?: Json | null
          address_display?: string | null
          booking_slug?: string | null
          business_hours?: Json | null
          business_type?: string | null
          created_at?: string | null
          email?: string | null
          is_active?: boolean | null
          name: string
          onboarding_status?: string
          outlet_id: string
          owner_user_id?: string | null
          phone?: string | null
          phone_number?: string | null
          reviews?: Json | null
          service_categories?: Json | null
          settings?: Json | null
          status?: string
          timezone?: string | null
          updated_at?: string | null
          website?: string | null
        }
        Update: {
          access_status?: string
          account_limit?: number
          address?: Json | null
          address_display?: string | null
          booking_slug?: string | null
          business_hours?: Json | null
          business_type?: string | null
          created_at?: string | null
          email?: string | null
          is_active?: boolean | null
          name?: string
          onboarding_status?: string
          outlet_id?: string
          owner_user_id?: string | null
          phone?: string | null
          phone_number?: string | null
          reviews?: Json | null
          service_categories?: Json | null
          settings?: Json | null
          status?: string
          timezone?: string | null
          updated_at?: string | null
          website?: string | null
        }
        Relationships: []
      }
      outstanding_transactions: {
        Row: {
          amount: number | null
          client_id: string
          description: string | null
          id: string
          is_manual: boolean | null
          new_balance: number | null
          outlet_id: string
          previous_balance: number | null
          timestamp: string | null
          type: string
        }
        Insert: {
          amount?: number | null
          client_id: string
          description?: string | null
          id: string
          is_manual?: boolean | null
          new_balance?: number | null
          outlet_id: string
          previous_balance?: number | null
          timestamp?: string | null
          type: string
        }
        Update: {
          amount?: number | null
          client_id?: string
          description?: string | null
          id?: string
          is_manual?: boolean | null
          new_balance?: number | null
          outlet_id?: string
          previous_balance?: number | null
          timestamp?: string | null
          type?: string
        }
        Relationships: [
          {
            foreignKeyName: "outstanding_transactions_client_id_fkey"
            columns: ["client_id"]
            isOneToOne: false
            referencedRelation: "clients"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "outstanding_transactions_outlet_id_fkey"
            columns: ["outlet_id"]
            isOneToOne: false
            referencedRelation: "outlets"
            referencedColumns: ["outlet_id"]
          },
        ]
      }
      packages: {
        Row: {
          category: string | null
          created_at: string | null
          description: string | null
          id: string
          name: string
          outlet_id: string
          points: number | null
          price: number | null
          services: Json | null
        }
        Insert: {
          category?: string | null
          created_at?: string | null
          description?: string | null
          id: string
          name?: string
          outlet_id: string
          points?: number | null
          price?: number | null
          services?: Json | null
        }
        Update: {
          category?: string | null
          created_at?: string | null
          description?: string | null
          id?: string
          name?: string
          outlet_id?: string
          points?: number | null
          price?: number | null
          services?: Json | null
        }
        Relationships: [
          {
            foreignKeyName: "packages_outlet_id_fkey"
            columns: ["outlet_id"]
            isOneToOne: false
            referencedRelation: "outlets"
            referencedColumns: ["outlet_id"]
          },
        ]
      }
      platform_admins: {
        Row: {
          created_at: string
          status: string
          user_id: string
        }
        Insert: {
          created_at?: string
          status?: string
          user_id: string
        }
        Update: {
          created_at?: string
          status?: string
          user_id?: string
        }
        Relationships: []
      }
      platform_audit_events: {
        Row: {
          action: string
          actor_email: string | null
          actor_uid: string | null
          affected_target: string
          id: string
          metadata: Json
          occurred_at: string
          outlet_id: string | null
          reason: string | null
          source: string
        }
        Insert: {
          action: string
          actor_email?: string | null
          actor_uid?: string | null
          affected_target: string
          id?: string
          metadata?: Json
          occurred_at?: string
          outlet_id?: string | null
          reason?: string | null
          source?: string
        }
        Update: {
          action?: string
          actor_email?: string | null
          actor_uid?: string | null
          affected_target?: string
          id?: string
          metadata?: Json
          occurred_at?: string
          outlet_id?: string | null
          reason?: string | null
          source?: string
        }
        Relationships: []
      }
      platform_monitoring_events: {
        Row: {
          correlation_id: string | null
          event_type: string
          id: string
          message: string
          metadata: Json
          occurred_at: string
          outlet_id: string | null
          service: string
          severity: string
        }
        Insert: {
          correlation_id?: string | null
          event_type: string
          id?: string
          message: string
          metadata?: Json
          occurred_at?: string
          outlet_id?: string | null
          service: string
          severity: string
        }
        Update: {
          correlation_id?: string | null
          event_type?: string
          id?: string
          message?: string
          metadata?: Json
          occurred_at?: string
          outlet_id?: string | null
          service?: string
          severity?: string
        }
        Relationships: []
      }
      point_transactions: {
        Row: {
          amount: number | null
          client_id: string
          description: string | null
          id: string
          is_manual: boolean | null
          new_balance: number | null
          outlet_id: string
          previous_balance: number | null
          timestamp: string | null
          type: string
        }
        Insert: {
          amount?: number | null
          client_id: string
          description?: string | null
          id: string
          is_manual?: boolean | null
          new_balance?: number | null
          outlet_id: string
          previous_balance?: number | null
          timestamp?: string | null
          type: string
        }
        Update: {
          amount?: number | null
          client_id?: string
          description?: string | null
          id?: string
          is_manual?: boolean | null
          new_balance?: number | null
          outlet_id?: string
          previous_balance?: number | null
          timestamp?: string | null
          type?: string
        }
        Relationships: [
          {
            foreignKeyName: "point_transactions_client_id_fkey"
            columns: ["client_id"]
            isOneToOne: false
            referencedRelation: "clients"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "point_transactions_outlet_id_fkey"
            columns: ["outlet_id"]
            isOneToOne: false
            referencedRelation: "outlets"
            referencedColumns: ["outlet_id"]
          },
        ]
      }
      points_credits: {
        Row: {
          client_id: string
          credited_at: string | null
          points: number
          sale_id: string
        }
        Insert: {
          client_id: string
          credited_at?: string | null
          points: number
          sale_id: string
        }
        Update: {
          client_id?: string
          credited_at?: string | null
          points?: number
          sale_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "points_credits_client_id_fkey"
            columns: ["client_id"]
            isOneToOne: false
            referencedRelation: "clients"
            referencedColumns: ["id"]
          },
        ]
      }
      products: {
        Row: {
          category: string | null
          fixed_commission_amount: number | null
          id: string
          name: string
          outlet_id: string
          price: number | null
          stock: number | null
        }
        Insert: {
          category?: string | null
          fixed_commission_amount?: number | null
          id: string
          name?: string
          outlet_id: string
          price?: number | null
          stock?: number | null
        }
        Update: {
          category?: string | null
          fixed_commission_amount?: number | null
          id?: string
          name?: string
          outlet_id?: string
          price?: number | null
          stock?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "products_outlet_id_fkey"
            columns: ["outlet_id"]
            isOneToOne: false
            referencedRelation: "outlets"
            referencedColumns: ["outlet_id"]
          },
        ]
      }
      profiles: {
        Row: {
          avatar_url: string | null
          created_at: string
          email: string | null
          full_name: string | null
          id: string
          phone: string | null
          updated_at: string
        }
        Insert: {
          avatar_url?: string | null
          created_at?: string
          email?: string | null
          full_name?: string | null
          id: string
          phone?: string | null
          updated_at?: string
        }
        Update: {
          avatar_url?: string | null
          created_at?: string
          email?: string | null
          full_name?: string | null
          id?: string
          phone?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      rewards: {
        Row: {
          cost: number | null
          icon: string | null
          id: string
          name: string
          outlet_id: string
        }
        Insert: {
          cost?: number | null
          icon?: string | null
          id: string
          name?: string
          outlet_id: string
        }
        Update: {
          cost?: number | null
          icon?: string | null
          id?: string
          name?: string
          outlet_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "rewards_outlet_id_fkey"
            columns: ["outlet_id"]
            isOneToOne: false
            referencedRelation: "outlets"
            referencedColumns: ["outlet_id"]
          },
        ]
      }
      services: {
        Row: {
          category: string | null
          category_id: string | null
          created_at: string | null
          description: string | null
          display_order: number | null
          duration: number | null
          icon_id: string | null
          id: string
          image_url: string | null
          is_commissionable: boolean | null
          is_promotion: boolean | null
          is_visible: boolean | null
          name: string
          outlet_id: string
          points: number | null
          price: number | null
          redeem_points: number | null
          redeem_points_enabled: boolean | null
        }
        Insert: {
          category?: string | null
          category_id?: string | null
          created_at?: string | null
          description?: string | null
          display_order?: number | null
          duration?: number | null
          icon_id?: string | null
          id: string
          image_url?: string | null
          is_commissionable?: boolean | null
          is_promotion?: boolean | null
          is_visible?: boolean | null
          name?: string
          outlet_id: string
          points?: number | null
          price?: number | null
          redeem_points?: number | null
          redeem_points_enabled?: boolean | null
        }
        Update: {
          category?: string | null
          category_id?: string | null
          created_at?: string | null
          description?: string | null
          display_order?: number | null
          duration?: number | null
          icon_id?: string | null
          id?: string
          image_url?: string | null
          is_commissionable?: boolean | null
          is_promotion?: boolean | null
          is_visible?: boolean | null
          name?: string
          outlet_id?: string
          points?: number | null
          price?: number | null
          redeem_points?: number | null
          redeem_points_enabled?: boolean | null
        }
        Relationships: [
          {
            foreignKeyName: "services_outlet_id_fkey"
            columns: ["outlet_id"]
            isOneToOne: false
            referencedRelation: "outlets"
            referencedColumns: ["outlet_id"]
          },
        ]
      }
      staff: {
        Row: {
          created_at: string | null
          email: string | null
          id: string
          name: string
          outlet_id: string
          permissions: Json | null
          phone: string | null
          photo_url: string | null
          profile_picture: string | null
          qualified_services: Json | null
          role: string | null
          weekly_hours: Json | null
        }
        Insert: {
          created_at?: string | null
          email?: string | null
          id: string
          name?: string
          outlet_id: string
          permissions?: Json | null
          phone?: string | null
          photo_url?: string | null
          profile_picture?: string | null
          qualified_services?: Json | null
          role?: string | null
          weekly_hours?: Json | null
        }
        Update: {
          created_at?: string | null
          email?: string | null
          id?: string
          name?: string
          outlet_id?: string
          permissions?: Json | null
          phone?: string | null
          photo_url?: string | null
          profile_picture?: string | null
          qualified_services?: Json | null
          role?: string | null
          weekly_hours?: Json | null
        }
        Relationships: [
          {
            foreignKeyName: "staff_outlet_id_fkey"
            columns: ["outlet_id"]
            isOneToOne: false
            referencedRelation: "outlets"
            referencedColumns: ["outlet_id"]
          },
        ]
      }
      transactions: {
        Row: {
          amount: number | null
          category: string | null
          client_id: string | null
          created_at: string | null
          date: string
          description: string | null
          id: string
          items: Json | null
          outlet_id: string
          outstanding: number | null
          parent_sale_id: string | null
          payment_method: string | null
          payment_status: string | null
          remarks: string | null
          status: string | null
          type: string
          voided: boolean | null
        }
        Insert: {
          amount?: number | null
          category?: string | null
          client_id?: string | null
          created_at?: string | null
          date?: string
          description?: string | null
          id: string
          items?: Json | null
          outlet_id: string
          outstanding?: number | null
          parent_sale_id?: string | null
          payment_method?: string | null
          payment_status?: string | null
          remarks?: string | null
          status?: string | null
          type: string
          voided?: boolean | null
        }
        Update: {
          amount?: number | null
          category?: string | null
          client_id?: string | null
          created_at?: string | null
          date?: string
          description?: string | null
          id?: string
          items?: Json | null
          outlet_id?: string
          outstanding?: number | null
          parent_sale_id?: string | null
          payment_method?: string | null
          payment_status?: string | null
          remarks?: string | null
          status?: string | null
          type?: string
          voided?: boolean | null
        }
        Relationships: [
          {
            foreignKeyName: "transactions_outlet_id_fkey"
            columns: ["outlet_id"]
            isOneToOne: false
            referencedRelation: "outlets"
            referencedColumns: ["outlet_id"]
          },
        ]
      }
      users: {
        Row: {
          created_at: string | null
          display_name: string | null
          email: string | null
          outlet_id: string | null
          role: string | null
          uid: string
        }
        Insert: {
          created_at?: string | null
          display_name?: string | null
          email?: string | null
          outlet_id?: string | null
          role?: string | null
          uid: string
        }
        Update: {
          created_at?: string | null
          display_name?: string | null
          email?: string | null
          outlet_id?: string | null
          role?: string | null
          uid?: string
        }
        Relationships: [
          {
            foreignKeyName: "users_outlet_id_fkey"
            columns: ["outlet_id"]
            isOneToOne: false
            referencedRelation: "outlets"
            referencedColumns: ["outlet_id"]
          },
        ]
      }
      vouchers: {
        Row: {
          created_at: string | null
          expiry_date: string | null
          id: string
          name: string
          outlet_id: string
          price: number | null
          purchased_at: string | null
          redeemed_at: string | null
          redemption_id: string | null
          secret_code: string | null
          service_ids: Json | null
          slug: string | null
          status: string
        }
        Insert: {
          created_at?: string | null
          expiry_date?: string | null
          id: string
          name?: string
          outlet_id: string
          price?: number | null
          purchased_at?: string | null
          redeemed_at?: string | null
          redemption_id?: string | null
          secret_code?: string | null
          service_ids?: Json | null
          slug?: string | null
          status?: string
        }
        Update: {
          created_at?: string | null
          expiry_date?: string | null
          id?: string
          name?: string
          outlet_id?: string
          price?: number | null
          purchased_at?: string | null
          redeemed_at?: string | null
          redemption_id?: string | null
          secret_code?: string | null
          service_ids?: Json | null
          slug?: string | null
          status?: string
        }
        Relationships: [
          {
            foreignKeyName: "vouchers_outlet_id_fkey"
            columns: ["outlet_id"]
            isOneToOne: false
            referencedRelation: "outlets"
            referencedColumns: ["outlet_id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      accept_outlet_invitation: {
        Args: { invitation_token: string }
        Returns: Json
      }
      append_platform_audit_event: {
        Args: {
          p_action: string
          p_affected_target: string
          p_metadata?: Json
          p_outlet_id: string
          p_reason?: string
          p_source?: string
        }
        Returns: string
      }
      can_manage_outlet_accounts: {
        Args: { p_outlet_id: string }
        Returns: boolean
      }
      change_outlet_member_role: {
        Args: { p_member_id: string; p_role: string }
        Returns: undefined
      }
      complete_merchant_onboarding: { Args: { payload: Json }; Returns: Json }
      create_merchant_workspace: {
        Args: {
          p_business_name: string
          p_business_type: string
          p_phone?: string
          p_request_id: string
        }
        Returns: Json
      }
      create_outlet_invitation: {
        Args: {
          invitation_role?: string
          invitee_email: string
          valid_hours?: number
        }
        Returns: Json
      }
      create_public_booking: {
        Args: {
          p_auth_uid?: string
          p_customer_name: string
          p_date: string
          p_email?: string
          p_outlet_id: string
          p_phone: string
          p_service_id: string
          p_staff_id?: string
          p_time: string
        }
        Returns: Json
      }
      current_portal_outlet_id: { Args: never; Returns: string }
      ensure_customer_profile: { Args: never; Returns: Json }
      ensure_identity_profiles: { Args: never; Returns: Json }
      get_public_available_slots: {
        Args: {
          p_date: string
          p_outlet_id: string
          p_service_id: string
          p_staff_id?: string
        }
        Returns: string[]
      }
      has_outlet_role: {
        Args: { p_outlet_id: string; p_roles: string[] }
        Returns: boolean
      }
      is_outlet_member: { Args: { p_outlet_id: string }; Returns: boolean }
      is_platform_admin: { Args: never; Returns: boolean }
      is_portal_admin: { Args: never; Returns: boolean }
      is_portal_platform_admin: { Args: never; Returns: boolean }
      merchant_adjust_client_credit: {
        Args: {
          p_amount: number
          p_client_id: string
          p_outlet_id: string
          p_staff_name?: string
          p_staff_remark?: string
          p_transaction_id?: string
          p_type: string
        }
        Returns: number
      }
      merchant_adjust_client_outstanding: {
        Args: {
          p_amount: number
          p_client_id: string
          p_outlet_id: string
          p_timestamp?: string
          p_type: string
        }
        Returns: string
      }
      merchant_adjust_client_points: {
        Args: {
          p_amount: number
          p_client_id: string
          p_description?: string
          p_is_manual?: boolean
          p_outlet_id: string
          p_type: string
        }
        Returns: string
      }
      merchant_credit_points_for_sale: {
        Args: {
          p_client_id: string
          p_outlet_id: string
          p_points: number
          p_sale_id: string
        }
        Returns: boolean
      }
      merchant_dashboard_aggregates: {
        Args: {
          p_outlet_id: string
          p_month_start: string
          p_month_end: string
          p_week_start: string
          p_week_end: string
          p_today: string
          p_yesterday: string
          p_prev_week_start: string
          p_prev_week_end: string
          p_prev_month_start: string
          p_prev_month_end: string
        }
        Returns: Json
      }
      merchant_monthly_report_summary: {
        Args: {
          p_outlet_id: string
          p_year: number
          p_month: number
        }
        Returns: Json
      }
      parse_time_to_minutes: { Args: { time_str: string }; Returns: number }
      public_voucher_confirm_redemption: {
        Args: { p_voucher_id: string }
        Returns: undefined
      }
      public_voucher_purchase: { Args: { p_voucher_id: string }; Returns: Json }
      resolve_merchant_access: { Args: never; Returns: Json }
      set_outlet_member_status: {
        Args: { p_member_id: string; p_status: string }
        Returns: undefined
      }
      slugify_booking_name: { Args: { value: string }; Returns: string }
      submit_public_review: {
        Args: {
          p_author?: string
          p_outlet_id: string
          p_rating?: number
          p_text?: string
        }
        Returns: Json
      }
      transfer_outlet_ownership: {
        Args: {
          p_confirmation: string
          p_new_owner: string
          p_outlet_id: string
        }
        Returns: undefined
      }
      upsert_frontend_customer_profile: {
        Args: { p_email?: string; p_name?: string }
        Returns: Json
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const

