import React, { useEffect, useState } from 'react';
import { RefreshCw } from 'lucide-react';
import { useSearchParams } from 'react-router-dom';
import { PlatformPageHeader, PlatformSection } from '../components/admin';
import { useOutletInspector } from '../components/admin/OutletInspectorContext';
import { Button, EmptyState, ErrorState, LoadingSkeleton, StatusBadge, fieldControlClassName } from '../components/ui';
import { outletService } from '../services/databaseService';
import { platformStep2Service, type IntegrationEvidence, type JobEvidence } from '../services/platformStep2Service';
import type { Outlet } from '../types';

const tone = (state:string) => state==='failed'||state==='error'||state==='needs_reauth'?'danger':state==='verified'||state==='succeeded'?'success':state==='running'||state==='provider_accepted'||state==='connected_unverified'?'brand':state==='pending'||state==='partial'?'warning':'neutral';
const isoDaysAgo=(days:number)=>new Date(Date.now()-days*86400000).toISOString();

const SuperAdminIntegrationsJobs:React.FC=()=>{
  const [params,setParams]=useSearchParams(); const [tab,setTab]=useState<'integrations'|'jobs'>(params.get('tab')==='jobs'?'jobs':'integrations');
  const { openOutletInspector } = useOutletInspector();
  const selectedOperation=params.get('operation');
  const requestedTab: 'integrations'|'jobs'=params.get('tab')==='jobs'?'jobs':'integrations';
  const requestedOutletId=params.get('outlet')||'';
  const requestedFrom=params.get('from')||isoDaysAgo(7).slice(0,10);
  const requestedTo=params.get('to')||new Date().toISOString().slice(0,10);
  const [outlets,setOutlets]=useState<Outlet[]>([]); const [outletId,setOutletId]=useState(params.get('outlet')||''); const [type,setType]=useState('all'); const [state,setState]=useState('all');
  const [from,setFrom]=useState(params.get('from')||isoDaysAgo(7).slice(0,10)); const [to,setTo]=useState(params.get('to')||new Date().toISOString().slice(0,10));
  const [integrations,setIntegrations]=useState<IntegrationEvidence[]>([]); const [jobs,setJobs]=useState<JobEvidence[]>([]); const [total,setTotal]=useState(0); const [page,setPage]=useState(1); const limit=25;
  const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null); const [schedulerState,setSchedulerState]=useState('not_instrumented');
  const load=async(nextPage=page,overrides:Partial<{tab:'integrations'|'jobs';outletId:string;type:string;state:string;from:string;to:string}>={})=>{const activeTab=overrides.tab||tab;const activeOutlet=overrides.outletId??outletId;const activeType=overrides.type??type;const activeState=overrides.state??state;const activeFrom=overrides.from??from;const activeTo=overrides.to??to;setLoading(true);setError(null);try{const outletRows=outlets.length?outlets:await outletService.getAll();setOutlets(outletRows);if(activeTab==='integrations'){const result=await platformStep2Service.integrations({outletId:activeOutlet,type:activeType,state:activeState,page:nextPage,limit});setIntegrations(result.rows);setTotal(result.total);}else{const result=await platformStep2Service.jobs({outletId:activeOutlet,type:activeType,state:activeState,from:activeFrom?new Date(`${activeFrom}T00:00:00`).toISOString():undefined,to:activeTo?new Date(`${activeTo}T23:59:59.999`).toISOString():undefined,page:nextPage,limit});setJobs(result.rows);setTotal(result.total);setSchedulerState(result.scheduler_instrumentation);}setPage(nextPage);}catch(value){setError(value instanceof Error?value.message:'Monitoring evidence could not be loaded.');}finally{setLoading(false);}};
  useEffect(()=>{setTab(requestedTab);setOutletId(requestedOutletId);setFrom(requestedFrom);setTo(requestedTo);setType('all');setState('all');void load(1,{tab:requestedTab,outletId:requestedOutletId,type:'all',state:'all',from:requestedFrom,to:requestedTo});},[requestedTab,selectedOperation,requestedOutletId,requestedFrom,requestedTo]);
  const changeTab=(next:'integrations'|'jobs')=>{setTab(next);setType('all');setState('all');setParams({tab:next},{replace:true});};
  return <div className="space-y-5"><PlatformPageHeader title="Integrations & jobs" description="Current state is shown only where durable backend evidence exists." action={<Button variant="secondary" onClick={()=>void load(1)}><RefreshCw className="h-4 w-4"/>Refresh</Button>}/>
    <div className="flex rounded-ui-md border border-[var(--line)] bg-[var(--bg-surface)] p-1"><button className={`min-h-10 flex-1 rounded-ui-sm text-sm font-semibold ${tab==='integrations'?'bg-[var(--brand-soft)] text-[var(--brand)]':''}`} onClick={()=>changeTab('integrations')}>Integrations</button><button className={`min-h-10 flex-1 rounded-ui-sm text-sm font-semibold ${tab==='jobs'?'bg-[var(--brand-soft)] text-[var(--brand)]':''}`} onClick={()=>changeTab('jobs')}>Jobs & operations</button></div>
    <div className="grid gap-2 rounded-ui-lg border border-[var(--line)] bg-[var(--bg-surface)] p-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-6"><select className={fieldControlClassName} value={outletId} onChange={e=>setOutletId(e.target.value)}><option value="">All outlets</option>{outlets.map(o=><option key={o.outletID} value={o.outletID}>{o.name||o.outletID}</option>)}</select><input className={fieldControlClassName} value={type==='all'?'':type} onChange={e=>setType(e.target.value||'all')} placeholder="Type (all)"/><input className={fieldControlClassName} value={state==='all'?'':state} onChange={e=>setState(e.target.value||'all')} placeholder="State (all)"/>{tab==='jobs'?<><input type="date" className={fieldControlClassName} value={from} onChange={e=>setFrom(e.target.value)}/><input type="date" className={fieldControlClassName} value={to} onChange={e=>setTo(e.target.value)}/></>:<div className="hidden xl:block"/>}<Button onClick={()=>void load(1)} disabled={loading}>Apply</Button></div>
    {tab==='integrations'?<div className="rounded-ui-md border border-[var(--info)]/25 bg-[var(--info-soft)] p-3 text-xs text-[var(--text-secondary)]">A saved credential or URL is reported as configured but unverified. Marketing “sent” means provider accepted, not confirmed delivery. Reminders are simulated.</div>:<div className="rounded-ui-md border border-[var(--warning)]/25 bg-[var(--warning-soft)] p-3 text-xs text-[var(--text-secondary)]">Retries are inspection-only: existing records do not provide every authorization, state, attempt, and idempotency guarantee required for safe replay. Scheduler run health is {schedulerState.replaceAll('_',' ')}.</div>}
    {error?<ErrorState message={error} onRetry={()=>load(page)}/>:null}
    <PlatformSection title={tab==='integrations'?'Integration evidence':'Job and operation evidence'} description={`${total.toLocaleString()} matching records · server paginated`}>
      {loading?<LoadingSkeleton rows={8} className="p-4"/>:tab==='integrations'?(!integrations.length?<EmptyState className="m-4" title="No integration evidence" description="No matching configuration or operation records are available."/>:<div className="divide-y divide-[var(--line)]">{integrations.map((row,index)=><button type="button" onClick={()=>openOutletInspector(row.outlet_id,'integrations')} key={`${row.outlet_id}-${row.integration_type}-${index}`} className="grid w-full gap-2 p-4 text-left hover:bg-[var(--bg-soft)] lg:grid-cols-[minmax(0,1fr)_auto]"><div className="min-w-0"><p className="truncate text-sm font-bold">{row.outlet_name} · {row.integration_type.replaceAll('_',' ')}</p><p className="mt-1 text-xs text-[var(--text-muted)]">{row.detail}</p>{row.latest_error?<p className="mt-1 break-words text-xs text-[var(--danger)]">{row.latest_error}</p>:null}</div><div className="flex flex-wrap items-center gap-2"><StatusBadge tone={tone(row.state)}>{row.state.replaceAll('_',' ')}</StatusBadge><span className="text-xs text-[var(--text-muted)]">Last verified: {row.last_verified_success?new Date(row.last_verified_success).toLocaleString():'Unavailable'}</span></div></button>)}</div>):(!jobs.length?<EmptyState className="m-4" title="No job evidence" description="The durable stores have no matching records."/>:<div className="divide-y divide-[var(--line)]">{jobs.map((row,index)=><button type="button" disabled={!row.outlet_id} onClick={()=>row.outlet_id&&openOutletInspector(row.outlet_id,'integrations')} key={`${row.job_type}-${row.reference_id}-${index}`} className={`grid w-full gap-2 p-4 text-left hover:bg-[var(--bg-soft)] lg:grid-cols-[minmax(0,1fr)_auto] ${selectedOperation&&row.reference_id===selectedOperation?'bg-[var(--brand-soft)] ring-2 ring-inset ring-[var(--brand)]':''}`}><div className="min-w-0"><p className="break-words text-sm font-bold">{row.job_type.replaceAll('_',' ')} · {row.outlet_name||row.outlet_id||'Platform'}</p><p className="mt-1 break-all font-mono text-[11px] text-[var(--text-muted)]">{row.reference_id||'No correlation ID'} · attempt {row.attempt_count}</p>{row.error?<p className="mt-1 break-words text-xs text-[var(--danger)]">{row.error}</p>:null}</div><div className="flex flex-wrap items-center gap-2"><StatusBadge tone={tone(row.state)}>{row.state.replaceAll('_',' ')}</StatusBadge><span className="text-xs text-[var(--text-muted)]">{new Date(row.started_at).toLocaleString()}{row.completed_at?` → ${new Date(row.completed_at).toLocaleString()}`:''}</span></div></button>)}</div>)}
      <div className="flex justify-between gap-3 border-t border-[var(--line)] p-3"><Button variant="secondary" disabled={page===1||loading} onClick={()=>void load(page-1)}>Previous</Button><span className="self-center text-xs text-[var(--text-muted)]">Page {page} of {Math.max(1,Math.ceil(total/limit))}</span><Button variant="secondary" disabled={page*limit>=total||loading} onClick={()=>void load(page+1)}>Next</Button></div>
    </PlatformSection>
  </div>;
};
export default SuperAdminIntegrationsJobs;
