import React, { useEffect, useState } from 'react';
import { ExternalLink, Plus, RefreshCw, ShieldCheck } from 'lucide-react';
import { Link, useSearchParams } from 'react-router-dom';
import { PlatformPageHeader, PlatformSection } from '../components/admin';
import { AppDrawer, Button, EmptyState, ErrorState, Field, LoadingSkeleton, StatusBadge, fieldControlClassName } from '../components/ui';
import { outletService } from '../services/databaseService';
import { platformStep2Service, type PlatformOperator, type SupportCase, type SupportCaseDetail } from '../services/platformStep2Service';
import { remoteAccessService } from '../services/remoteAccessService';
import type { Outlet } from '../types';

const priorityTone = (priority: string) => priority === 'urgent' ? 'danger' : priority === 'high' ? 'warning' : 'neutral';
const statusTone = (status: string) => status === 'resolved' ? 'success' : status === 'waiting_on_merchant' ? 'warning' : status === 'in_progress' ? 'brand' : 'neutral';

const SuperAdminSupport: React.FC = () => {
  const [params, setParams] = useSearchParams();
  const [rows, setRows] = useState<SupportCase[]>([]); const [total, setTotal] = useState(0); const [page, setPage] = useState(1); const limit=20;
  const [outlets, setOutlets] = useState<Outlet[]>([]); const [operators, setOperators] = useState<PlatformOperator[]>([]);
  const [search,setSearch]=useState(''); const [status,setStatus]=useState('all'); const [priority,setPriority]=useState('all'); const [category,setCategory]=useState('all'); const [outletId,setOutletId]=useState('');
  const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null); const [busy,setBusy]=useState(false);
  const [detail,setDetail]=useState<SupportCaseDetail|null>(null); const [createOpen,setCreateOpen]=useState(false);
  const [form,setForm]=useState({outletId:'',category:'operations',priority:'normal',subject:'',description:'',assignedTo:'',referenceType:'',referenceId:''});
  const [note,setNote]=useState(''); const [resolution,setResolution]=useState(''); const [referenceType,setReferenceType]=useState('booking'); const [referenceId,setReferenceId]=useState('');

  const load = async(nextPage=page) => { setLoading(true);setError(null);try { const [cases, outletRows, operatorRows]=await Promise.all([platformStep2Service.supportCases({search,status,priority,category,outletId,page:nextPage,limit}),outlets.length?Promise.resolve(outlets):outletService.getAll(),operators.length?Promise.resolve(operators):platformStep2Service.supportOperators()]);setRows(cases.rows);setTotal(cases.total);setPage(nextPage);setOutlets(outletRows);setOperators(operatorRows); } catch(value){setError(value instanceof Error?value.message:'Support cases could not be loaded.');} finally{setLoading(false);} };
  const openCase=async(id:string)=>{setBusy(true);setError(null);try{const value=await platformStep2Service.supportDetail(id);setDetail(value);setParams((current)=>{const next=new URLSearchParams(current);next.set('case',id);return next;},{replace:true});}catch(value){setError(value instanceof Error?value.message:'Support case could not be loaded.');}finally{setBusy(false);}};
  useEffect(()=>{void (async()=>{await load(1);const id=params.get('case');if(id)await openCase(id);})();},[]);
  const closeDetail=()=>{setDetail(null);setParams((current)=>{const next=new URLSearchParams(current);next.delete('case');return next;},{replace:true});};
  const create=async()=>{setBusy(true);setError(null);try{const references=form.referenceType&&form.referenceId?[{type:form.referenceType,id:form.referenceId}]:[];const id=await platformStep2Service.createSupportCase({...form,references});setCreateOpen(false);setForm({outletId:'',category:'operations',priority:'normal',subject:'',description:'',assignedTo:'',referenceType:'',referenceId:''});await load(1);await openCase(id);}catch(value){setError(value instanceof Error?value.message:'Support case could not be created.');}finally{setBusy(false);}};
  const mutate=async(action:string,input:Record<string,string|undefined>={})=>{if(!detail)return;setBusy(true);setError(null);try{await platformStep2Service.updateSupportCase(detail.case.id,action,{...input,expectedUpdatedAt:detail.case.updated_at});setDetail(await platformStep2Service.supportDetail(detail.case.id));await load(page);}catch(value){setError(value instanceof Error?value.message:'Support case update failed.');}finally{setBusy(false);}};
  const addNote=async()=>{await mutate('add_note',{note});setNote('');};
  const addReference=async()=>{if(!detail)return;setBusy(true);try{await platformStep2Service.addSupportReference(detail.case.id,referenceType,referenceId);setDetail(await platformStep2Service.supportDetail(detail.case.id));setReferenceId('');await load(page);}catch(value){setError(value instanceof Error?value.message:'Reference could not be added.');}finally{setBusy(false);}};
  const remote=async()=>{if(!detail)return;setBusy(true);try{await remoteAccessService.enter(detail.case.outlet_id);window.location.assign('/dashboard');}catch(value){setError(value instanceof Error?value.message:'Remote access could not be started.');setBusy(false);}};

  return <div className="space-y-5">
    <PlatformPageHeader title="Merchant support" description="Internal platform cases with outlet-scoped references and immutable history. No external notifications are sent." action={<Button onClick={()=>setCreateOpen(true)}><Plus className="h-4 w-4"/>New case</Button>}/>
    <div className="grid gap-2 rounded-ui-lg border border-[var(--line)] bg-[var(--bg-surface)] p-3 sm:grid-cols-2 xl:grid-cols-[2fr_repeat(4,1fr)_auto]">
      <input className={fieldControlClassName} value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search subject or case ID" aria-label="Search support cases"/>
      <select className={fieldControlClassName} value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All statuses</option><option value="open">Open</option><option value="in_progress">In progress</option><option value="waiting_on_merchant">Waiting on merchant</option><option value="resolved">Resolved</option></select>
      <select className={fieldControlClassName} value={priority} onChange={e=>setPriority(e.target.value)}><option value="all">All priorities</option><option value="urgent">Urgent</option><option value="high">High</option><option value="normal">Normal</option><option value="low">Low</option></select>
      <select className={fieldControlClassName} value={category} onChange={e=>setCategory(e.target.value)}><option value="all">All categories</option>{['account','access','booking','sales','integration','operations','other'].map(v=><option key={v} value={v}>{v}</option>)}</select>
      <select className={fieldControlClassName} value={outletId} onChange={e=>setOutletId(e.target.value)}><option value="">All outlets</option>{outlets.map(o=><option key={o.outletID} value={o.outletID}>{o.name||o.outletID}</option>)}</select>
      <Button onClick={()=>void load(1)} disabled={loading}><RefreshCw className="h-4 w-4"/>Apply</Button>
    </div>
    {error?<ErrorState message={error} onRetry={()=>load(page)}/>:null}
    <PlatformSection title="Cases" description={`${total.toLocaleString()} matching cases · server paginated`}>
      {loading?<LoadingSkeleton rows={7} className="p-4"/>:!rows.length?<EmptyState className="m-4" title="No support cases" description="Create a case or change the filters."/>:<div className="divide-y divide-[var(--line)]">{rows.map(row=><button type="button" key={row.id} onClick={()=>void openCase(row.id)} className="grid w-full gap-2 p-4 text-left hover:bg-[var(--bg-soft)] sm:grid-cols-[minmax(0,1fr)_auto]"><div className="min-w-0"><p className="truncate text-sm font-bold">{row.subject}</p><p className="mt-1 text-xs text-[var(--text-muted)]">{row.outlet_name} · {row.category} · {row.assigned_name||'Unassigned'}</p></div><div className="flex flex-wrap items-center gap-2"><StatusBadge tone={priorityTone(row.priority)}>{row.priority}</StatusBadge><StatusBadge tone={statusTone(row.status)}>{row.status.replaceAll('_',' ')}</StatusBadge><span className="text-xs text-[var(--text-muted)]">{new Date(row.updated_at).toLocaleString()}</span></div></button>)}</div>}
      <div className="flex justify-between gap-3 border-t border-[var(--line)] p-3"><Button variant="secondary" disabled={page===1||loading} onClick={()=>void load(page-1)}>Previous</Button><span className="self-center text-xs text-[var(--text-muted)]">Page {page} of {Math.max(1,Math.ceil(total/limit))}</span><Button variant="secondary" disabled={page*limit>=total||loading} onClick={()=>void load(page+1)}>Next</Button></div>
    </PlatformSection>

    <AppDrawer open={createOpen} onClose={()=>setCreateOpen(false)} title="Create support case" description="All fields remain internal to platform administrators." variant="right" busy={busy} footer={<div className="flex justify-end gap-2"><Button variant="secondary" onClick={()=>setCreateOpen(false)}>Cancel</Button><Button onClick={()=>void create()} disabled={busy||!form.outletId||form.subject.trim().length<3||form.description.trim().length<3}>Create case</Button></div>}>
      <div className="space-y-4"><Field id="support-outlet" label="Outlet" required><select id="support-outlet" className={fieldControlClassName} value={form.outletId} onChange={e=>setForm({...form,outletId:e.target.value})}><option value="">Select outlet</option>{outlets.map(o=><option key={o.outletID} value={o.outletID}>{o.name||o.outletID}</option>)}</select></Field><div className="grid grid-cols-2 gap-3"><Field id="support-category" label="Category"><select id="support-category" className={fieldControlClassName} value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{['account','access','booking','sales','integration','operations','other'].map(v=><option key={v}>{v}</option>)}</select></Field><Field id="support-priority" label="Priority"><select id="support-priority" className={fieldControlClassName} value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}>{['low','normal','high','urgent'].map(v=><option key={v}>{v}</option>)}</select></Field></div><Field id="support-subject" label="Subject" required><input id="support-subject" className={fieldControlClassName} value={form.subject} maxLength={160} onChange={e=>setForm({...form,subject:e.target.value})}/></Field><Field id="support-description" label="Description" required><textarea id="support-description" className={`${fieldControlClassName} h-32 py-2`} value={form.description} maxLength={5000} onChange={e=>setForm({...form,description:e.target.value})}/></Field><Field id="support-assignee" label="Assignee"><select id="support-assignee" className={fieldControlClassName} value={form.assignedTo} onChange={e=>setForm({...form,assignedTo:e.target.value})}><option value="">Unassigned</option>{operators.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></Field><div className="grid grid-cols-[140px_1fr] gap-2"><select className={fieldControlClassName} value={form.referenceType} onChange={e=>setForm({...form,referenceType:e.target.value})}><option value="">No reference</option>{['booking','sale','integration','operation'].map(v=><option key={v}>{v}</option>)}</select><input className={fieldControlClassName} value={form.referenceId} onChange={e=>setForm({...form,referenceId:e.target.value})} placeholder="Reference ID"/></div></div>
    </AppDrawer>

    <AppDrawer open={Boolean(detail)} onClose={closeDetail} title={detail?.case.subject||'Support case'} description={detail?`${detail.case.outlet_name} · ${detail.case.id}`:undefined} variant="right" busy={busy} headerActions={detail?<div className="flex gap-2"><Link to={`/admin/subscribers?outlet=${encodeURIComponent(detail.case.outlet_id)}`} className="inline-flex h-8 items-center gap-1 rounded-ui-sm border border-[var(--line)] px-2 text-xs font-semibold"><ExternalLink className="h-3 w-3"/>Inspector</Link><Button size="sm" variant="secondary" onClick={()=>void remote()}><ShieldCheck className="h-3.5 w-3.5"/>Remote</Button></div>:null}>
      {detail?<div className="space-y-5"><div className="flex flex-wrap gap-2"><StatusBadge tone={priorityTone(detail.case.priority)}>{detail.case.priority}</StatusBadge><StatusBadge tone={statusTone(detail.case.status)}>{detail.case.status.replaceAll('_',' ')}</StatusBadge><StatusBadge>{detail.case.category}</StatusBadge></div><p className="whitespace-pre-wrap text-sm text-[var(--text-secondary)]">{detail.case.description}</p>
      <div className="space-y-3 rounded-ui-md border border-[var(--line)] p-3"><p className="text-xs font-bold uppercase text-[var(--text-muted)]">Case controls</p><select className={fieldControlClassName} value={detail.case.assigned_to||''} onChange={e=>void mutate('assign',{assignedTo:e.target.value})}><option value="">Unassigned</option>{operators.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select>{detail.case.status!=='resolved'?<div className="grid grid-cols-2 gap-2"><Button variant="secondary" onClick={()=>void mutate('set_status',{status:'in_progress'})}>In progress</Button><Button variant="secondary" onClick={()=>void mutate('set_status',{status:'waiting_on_merchant'})}>Waiting</Button></div>:<Button variant="secondary" onClick={()=>void mutate('reopen',{note})}>Reopen case</Button>}{detail.case.status!=='resolved'?<><textarea className={`${fieldControlClassName} h-20 py-2`} value={resolution} onChange={e=>setResolution(e.target.value)} placeholder="Resolution summary"/><Button fullWidth onClick={()=>void mutate('resolve',{resolutionSummary:resolution})} disabled={resolution.trim().length<3}>Resolve case</Button></>:detail.case.resolution_summary?<p className="text-sm"><strong>Resolution:</strong> {detail.case.resolution_summary}</p>:null}</div>
      <div className="space-y-2"><p className="text-xs font-bold uppercase text-[var(--text-muted)]">Internal note</p><textarea className={`${fieldControlClassName} h-20 py-2`} value={note} onChange={e=>setNote(e.target.value)} placeholder="Visible only to platform administrators"/><Button variant="secondary" onClick={()=>void addNote()} disabled={note.trim().length<2}>Add note</Button></div>
      <div className="space-y-2"><p className="text-xs font-bold uppercase text-[var(--text-muted)]">References</p>{detail.references.map(ref=><p key={ref.id} className="break-all rounded-ui-sm bg-[var(--bg-soft)] p-2 text-xs">{ref.entity_type}: {ref.reference_id}</p>)}<div className="grid grid-cols-[120px_1fr] gap-2"><select className={fieldControlClassName} value={referenceType} onChange={e=>setReferenceType(e.target.value)}>{['booking','sale','integration','operation'].map(v=><option key={v}>{v}</option>)}</select><input className={fieldControlClassName} value={referenceId} onChange={e=>setReferenceId(e.target.value)} placeholder="Reference ID"/></div><Button variant="secondary" onClick={()=>void addReference()} disabled={!referenceId.trim()}>Add reference</Button></div>
      <div className="space-y-2"><p className="text-xs font-bold uppercase text-[var(--text-muted)]">History</p>{detail.events.map(event=><div key={event.id} className="border-l-2 border-[var(--line)] pl-3 text-xs"><p className="font-semibold">{event.event_type.replaceAll('_',' ')} · {event.actor_email||event.actor_uid}</p>{event.note?<p className="mt-1 whitespace-pre-wrap text-[var(--text-secondary)]">{event.note}</p>:null}<p className="mt-1 text-[var(--text-muted)]">{new Date(event.created_at).toLocaleString()}</p></div>)}</div></div>:null}
    </AppDrawer>
  </div>;
};

export default SuperAdminSupport;
