CREATE OR REPLACE FUNCTION public.platform_activity_page(p_kind text,p_start_date date,p_end_date date,p_outlet_id text DEFAULT NULL,p_limit integer DEFAULT 25,p_offset integer DEFAULT 0)
RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=public AS $$
DECLARE v_rows jsonb; v_total bigint;
BEGIN
  IF NOT public.is_platform_admin() THEN RAISE EXCEPTION 'Platform administrator access required'; END IF;
  IF p_start_date IS NULL OR p_end_date IS NULL OR p_end_date < p_start_date OR p_end_date - p_start_date > 366 THEN RAISE EXCEPTION 'Choose a valid range of at most 367 days'; END IF;
  IF p_kind NOT IN ('bookings_created','appointments_scheduled','appointments_completed','appointments_cancelled','failed_operations','failed_messages','unresolved_support') THEN RAISE EXCEPTION 'Unsupported activity kind'; END IF;
 WITH bounds AS (SELECT o.outlet_id,o.name,CASE WHEN EXISTS(SELECT 1 FROM pg_timezone_names z WHERE z.name=o.timezone) THEN o.timezone ELSE 'UTC' END tz,p_start_date::timestamp AT TIME ZONE (CASE WHEN EXISTS(SELECT 1 FROM pg_timezone_names z WHERE z.name=o.timezone) THEN o.timezone ELSE 'UTC' END) utc_start,(p_end_date+1)::timestamp AT TIME ZONE (CASE WHEN EXISTS(SELECT 1 FROM pg_timezone_names z WHERE z.name=o.timezone) THEN o.timezone ELSE 'UTC' END) utc_end FROM public.outlets o WHERE p_outlet_id IS NULL OR o.outlet_id=p_outlet_id), activity AS (
  SELECT a.id,b.outlet_id,b.name outlet_name,a.status state,a.created_at occurred_at,a.date||' '||a.time scheduled_for,a.source,NULL::text detail FROM public.appointments a JOIN bounds b ON b.outlet_id=a.outlet_id WHERE p_kind='bookings_created' AND a.created_at>=b.utc_start AND a.created_at < b.utc_end
  UNION ALL SELECT a.id,b.outlet_id,b.name,a.status,a.created_at,a.date||' '||a.time,a.source,NULL FROM public.appointments a JOIN bounds b ON b.outlet_id=a.outlet_id WHERE p_kind='appointments_scheduled' AND a.date~'^\d{4}-\d{2}-\d{2}$' AND a.date::date BETWEEN p_start_date AND p_end_date
  UNION ALL SELECT a.id,b.outlet_id,b.name,a.status,a.completed_at,a.date||' '||a.time,a.source,NULL FROM public.appointments a JOIN bounds b ON b.outlet_id=a.outlet_id WHERE p_kind='appointments_completed' AND a.completed_at>=b.utc_start AND a.completed_at < b.utc_end
  UNION ALL SELECT a.id,b.outlet_id,b.name,a.status,a.cancelled_at,a.date||' '||a.time,a.source,NULL FROM public.appointments a JOIN bounds b ON b.outlet_id=a.outlet_id WHERE p_kind='appointments_cancelled' AND a.cancelled_at>=b.utc_start AND a.cancelled_at < b.utc_end
  UNION ALL SELECT op.id::text,coalesce(op.outlet_id,''),coalesce(b.name,'Platform'),op.state,coalesce(op.completed_at,op.started_at),NULL,op.action,public.platform_sanitize_error(op.result->>'error') FROM public.platform_admin_operations op LEFT JOIN bounds b ON b.outlet_id=op.outlet_id WHERE p_kind='failed_operations' AND op.state IN ('failed','partial') AND (p_outlet_id IS NULL OR op.outlet_id=p_outlet_id) AND op.started_at>=coalesce(b.utc_start,p_start_date::timestamp AT TIME ZONE 'UTC') AND op.started_at < coalesce(b.utc_end,(p_end_date+1)::timestamp AT TIME ZONE 'UTC')
  UNION ALL SELECT d.id,d.outlet_id,b.name,d.status,d.updated_at,NULL,d.channel,public.platform_sanitize_error(d.last_error) FROM public.marketing_campaign_deliveries d JOIN bounds b ON b.outlet_id=d.outlet_id WHERE p_kind='failed_messages' AND d.status='failed' AND d.updated_at>=b.utc_start AND d.updated_at < b.utc_end
  UNION ALL SELECT c.id::text,c.outlet_id,b.name,c.status,c.updated_at,NULL,c.category,c.subject FROM public.platform_support_cases c JOIN bounds b ON b.outlet_id=c.outlet_id WHERE p_kind='unresolved_support' AND c.status<>'resolved'
 ) SELECT count(*) INTO v_total FROM activity;
 WITH bounds AS (SELECT o.outlet_id,o.name,CASE WHEN EXISTS(SELECT 1 FROM pg_timezone_names z WHERE z.name=o.timezone) THEN o.timezone ELSE 'UTC' END tz,p_start_date::timestamp AT TIME ZONE (CASE WHEN EXISTS(SELECT 1 FROM pg_timezone_names z WHERE z.name=o.timezone) THEN o.timezone ELSE 'UTC' END) utc_start,(p_end_date+1)::timestamp AT TIME ZONE (CASE WHEN EXISTS(SELECT 1 FROM pg_timezone_names z WHERE z.name=o.timezone) THEN o.timezone ELSE 'UTC' END) utc_end FROM public.outlets o WHERE p_outlet_id IS NULL OR o.outlet_id=p_outlet_id), activity AS (
  SELECT a.id,b.outlet_id,b.name outlet_name,a.status state,a.created_at occurred_at,a.date||' '||a.time scheduled_for,a.source,NULL::text detail FROM public.appointments a JOIN bounds b ON b.outlet_id=a.outlet_id WHERE p_kind='bookings_created' AND a.created_at>=b.utc_start AND a.created_at < b.utc_end
  UNION ALL SELECT a.id,b.outlet_id,b.name,a.status,a.created_at,a.date||' '||a.time,a.source,NULL FROM public.appointments a JOIN bounds b ON b.outlet_id=a.outlet_id WHERE p_kind='appointments_scheduled' AND a.date~'^\d{4}-\d{2}-\d{2}$' AND a.date::date BETWEEN p_start_date AND p_end_date
  UNION ALL SELECT a.id,b.outlet_id,b.name,a.status,a.completed_at,a.date||' '||a.time,a.source,NULL FROM public.appointments a JOIN bounds b ON b.outlet_id=a.outlet_id WHERE p_kind='appointments_completed' AND a.completed_at>=b.utc_start AND a.completed_at < b.utc_end
  UNION ALL SELECT a.id,b.outlet_id,b.name,a.status,a.cancelled_at,a.date||' '||a.time,a.source,NULL FROM public.appointments a JOIN bounds b ON b.outlet_id=a.outlet_id WHERE p_kind='appointments_cancelled' AND a.cancelled_at>=b.utc_start AND a.cancelled_at < b.utc_end
  UNION ALL SELECT op.id::text,coalesce(op.outlet_id,''),coalesce(b.name,'Platform'),op.state,coalesce(op.completed_at,op.started_at),NULL,op.action,public.platform_sanitize_error(op.result->>'error') FROM public.platform_admin_operations op LEFT JOIN bounds b ON b.outlet_id=op.outlet_id WHERE p_kind='failed_operations' AND op.state IN ('failed','partial') AND (p_outlet_id IS NULL OR op.outlet_id=p_outlet_id) AND op.started_at>=coalesce(b.utc_start,p_start_date::timestamp AT TIME ZONE 'UTC') AND op.started_at < coalesce(b.utc_end,(p_end_date+1)::timestamp AT TIME ZONE 'UTC')
  UNION ALL SELECT d.id,d.outlet_id,b.name,d.status,d.updated_at,NULL,d.channel,public.platform_sanitize_error(d.last_error) FROM public.marketing_campaign_deliveries d JOIN bounds b ON b.outlet_id=d.outlet_id WHERE p_kind='failed_messages' AND d.status='failed' AND d.updated_at>=b.utc_start AND d.updated_at < b.utc_end
  UNION ALL SELECT c.id::text,c.outlet_id,b.name,c.status,c.updated_at,NULL,c.category,c.subject FROM public.platform_support_cases c JOIN bounds b ON b.outlet_id=c.outlet_id WHERE p_kind='unresolved_support' AND c.status<>'resolved'
 ) SELECT coalesce(jsonb_agg(to_jsonb(x)),'[]'::jsonb) INTO v_rows FROM (SELECT * FROM activity ORDER BY occurred_at DESC NULLS LAST,id LIMIT least(greatest(p_limit,1),100) OFFSET greatest(p_offset,0)) x;
 RETURN jsonb_build_object('rows',v_rows,'total',v_total);
END $$;

REVOKE ALL ON FUNCTION public.platform_activity_page(text,date,date,text,integer,integer) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.platform_activity_page(text,date,date,text,integer,integer) TO authenticated;